---
- name: create directory
  file:
    path: '/var/lib/{{registry.name}}'
    state: 'directory'
    mode: '0700'

- name: inspect registry service
  command: 'docker service inspect {{registry.name}}'
  register: registry_service

- name: run registry service
  command: >
    docker service create
      --name {{registry.name}}
      --publish 5000:5000
      --constraint 'node.hostname == {{ansible_hostname}}'
      --mount type=bind,source=/var/lib/{{registry.name}},destination=/var/lib/registry
        registry:2
  when: registry_service.stdout.find('no such service') != -1

- name: upload nginx configuration
  template:
    src: 'registry.conf'
    dest: '/etc/nginx/sites-enabled/registry.conf'
  notify:
    - restart openresty
